/**
 *
 * $Id$
 */
package aml.validation;

import aml.CAEXContainer;
import aml.COLLADAContainer;
import aml.PLCopenContainer;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link aml.AMLRoot}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AMLRootValidator {
	boolean validate();

	boolean validateColladacontainer(EList<COLLADAContainer> value);
	boolean validatePlcopencontainer(EList<PLCopenContainer> value);
	boolean validateCaexcontainer(EList<CAEXContainer> value);

	boolean validateProjectName(String value);
}
