<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="aml" nsURI="http://edu.kit.ipd.sdq.aml" nsPrefix="AML">
  <eClassifiers xsi:type="ecore:EClass" name="AMLRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="colladacontainer" upperBound="-1"
        eType="#//COLLADAContainer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="plcopencontainer" upperBound="-1"
        eType="#//PLCopenContainer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="caexcontainer" lowerBound="1"
        upperBound="-1" eType="#//CAEXContainer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectName" lowerBound="1"
        eType="ecore:EDataType ../../org.khronos.collada/model/collada.ecore#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CAEXContainer" eSuperTypes="#//ModelContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="caexModel" lowerBound="1"
        eType="ecore:EClass ../../org.automationml.caex/model/CAEX.ecore#//CAEXFile"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="COLLADAContainer" eSuperTypes="#//ModelContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="colladaModel" lowerBound="1"
        eType="ecore:EClass ../../org.khronos.collada/model/collada.ecore#//COLLADAType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PLCopenContainer" eSuperTypes="#//ModelContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="plcopenModel" lowerBound="1"
        eType="ecore:EClass ../../org.plcopen.xml.tc60201/model/tc60201.ecore#//ProjectType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelContainer" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
